### ISSUE TITLE
Prototype relies on javascript number behaviour

### ISSUE THREAD

**Issue by lalexgap** [statechannels/dispute-game#29]
Unfortunately Solidity doesn't have support for [fixed point numbers.](https://docs.soliditylang.org/en/v0.8.7/types.html?highlight=fixed%20point#fixed-point-numbers). Instead solidity [rounds to 0 ](https://docs.soliditylang.org/en/v0.8.7/types.html?highlight=division#division) when dividing numbers.

To simulate that behaviour in our prototype I have called `Math.floor` whenever we divide a value. This [causes the tests to fail](https://github.com/statechannels/dispute-game/tree/ag/solidity-math).

**Comment by andrewgordstewart** [comment]
sanity check: why can't I observe the failing test through GitHub?

![Screen Shot 2021-09-20 at 11 45 26 AM](https://user-images.githubusercontent.com/8432675/134057138-a89d38c8-bc3d-47df-b9e0-f8831352facf.png)

**Comment by lalexgap** [comment]
> sanity check: why can't I observe the failing test through GitHub?
> 
> ![Screen Shot 2021-09-20 at 11 45 26 AM](https://user-images.githubusercontent.com/8432675/134057138-a89d38c8-bc3d-47df-b9e0-f8831352facf.png)

It looks like GH actions don't get triggered unless there's an actual created PR. Now that I've created the PR you can see the failure [here](https://github.com/statechannels/dispute-game/pull/31)

**Comment by kerzhner** [comment]
@lalexgap anything else that remains here?

**Comment by lalexgap** [comment]
> @lalexgap anything else that remains here?

No, I think this is complete with your PR.
